### ISSUE TITLE
Runtime issue when building from source

### ISSUE THREAD

**Issue by MostHated** [greggbjensen/power-runner#47]
Final Edit -- Ok, it took the entire day, but I finally got it figured out. Apparently, the biggest thing was I had to run VSCode as admin, which feels like a bad thing to have to do, but it works. Then I had to run

```sh
npm install pkg-up
npm install --save sqlite3
```
followed by `yarn run electron-rebuild`, which looks like it gave me a folder in the sqlite lib named electron-v13.1-win32-x64, but then the app was looking for electron-v13.6-win32-x64, so I tried simply renaming it, and then it finally fully worked.

I am sure all the trouble was mostly due to having no real experience with electron/angular and only a little node, but at least its working. :+1: 

---

Edit - I should mention that using the precompiled binary works just fine, it's just building myself seems to have an issue.

Double Edit - Looking through node-script.service.ts, I am wondering if the way it's determining what paths to use has something to do with it. My desktop is linux and I am running Windows in a VM, so I wonder if node/electron is not getting back the win32 values that it is expecting for one of the checks somewhere as sometimes VMs don't always report back standard values that a bare-metal install would. Though, the fact that the actual path in the error seems correct kind of throws off that theory. I might just have to play around with things and see what happens.

-- The above doesn't seem to be the case. logging  process.platform to console showed win32. So that is out.

---

Hey there, I do apologize, as I am not well versed in JS/Node/Electron. There may very well be something I am doing incorrectly, but when I attempt to build from source and then use yarn run start, when I select a script folder and then select an actual script, it just sits there spinning the loading animation indefinitely and shows the following output in the console.

<details>
<summary>Console Output</summary>

```sh
Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Windows\\system32\\cmd.exe',
  path: 'C:\\Windows\\system32\\cmd.exe',
  spawnargs: [
    '/d',
    '/s',
    '/c',
    '""C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe" "C:\\Users\\DANT\\Documents\\GitHub\\power-runner\\dist\\electron\\powershell\\GetCommandMetadata.ps1" "C:\\Users\\DANT\\Documents\\GitHub\\power-runner\\samples\\attributes\\DateParams.ps1""'
  ],
  cmd: '"C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe" "C:\\Users\\DANT\\Documents\\GitHub\\power-runner\\dist\\electron\\powershell\\GetCommandMetadata.ps1" "C:\\Users\\DANT\\Documents\\GitHub\\power-runner\\samples\\attributes\\DateParams.ps1"'
}

```

</details>

The message feels like it might be unable to locate cmd on the $PATH, but I double-checked from the term session I ran the start command from and it was available, it contained all the typical items within $env:PATH, ex. "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;".  I feel that I must be missing some step or something?

I cloned repo, ran yarn, made sure I had the -g windows-build-tools (though a message from that said it may not be necessary) and then did yarn start run. Out of the gate it came back saying 

```shell
An unhandled exception occurred: The target entry-point "@angular/material-moment-adapter" has missing dependencies:
 - moment
```
So I did `yarn add moment` and then it was able to build and overall runs fine, just has the mentioned issue.

Thanks,
-MH

**Comment by greggbjensen** [comment]
@MostHated I am glad you were able to figure it out.  Please let me know if you run into anything else.
